package edu.brown.cs.student.main.data.ACS;

public class ACS {

  // Note: Each of the fields match the JSON properties exactly... Moshi IS case-sensitive!
  private String state;
  // Note: we make the field 'final' to keep us from overwriting the List itself, not its contents!
  private String county;
  private double broadband;

  /*public ACS(List<String> ingredients) {
      this.ingredients.addAll(ingredients);
    }
  */
  /**
   * Constructs a full soup! A tried and true recipe that has been past down!
   *
   * @param state
   * @param county
   * @param broadband
   */
  public ACS(String state, String county, float broadband) {
    this.state = state;
    this.county = county;
    this.broadband = broadband;
  }

  //  public List<String> getCounty() {
  //    return this.county;
  //  }
  //
  //  public String getState() {
  //    return this.state;
  //  }
  //
  //  public void setSoupName(String soupName) {
  //    this.soupName = soupName;
  //  }

  /**
   * Static factory method to make testing easier. Produces a Soup based on parameters and
   * ingredients. Does *not* produce ActualFlavorExceptions, even if the chef is timid.
   *
   * @param ingredients the set of ingredients to try mixing together
   * @return the new Soup object
   */
  //  public static Soup buildNoExceptions(String name, List<String> ingredients) {
  //    Soup result = new Soup(ingredients);
  //    result.setSoupName(name);
  //    return result;
  //  }

  /**
   * Override the toString to be a little more informative.
   *
   * @return
   */
  @Override
  public String toString() {
    return (this.county + ", " + this.state + "has broadband:" + this.broadband).toString();
  }

  /** auto-generated by IntelliJ Code -> generate */
  //  @Override
  //  public boolean equals(Object o) {
  //    if (this == o) return true;
  //    if (o == null || getClass() != o.getClass()) return false;
  //    Soup soup = (Soup) o;
  //    return Objects.equals(this.ingredients, soup.getIngredients());
  //  }

  /** auto-generated by IntelliJ Code -> generate */
  //  @Override
  //  public int hashCode() {
  //    return Objects.hash(this.ingredients);
  //  }
  // }

}
